### ISSUE TITLE
Faulty Navbar : Links not apperaing in small screen devices.

### ISSUE THREAD

**Issue by snitin315** [Shagunaawasthi/IOSD-Website#5]
The navbar is not working as expected for pages other than index page.

**To Reproduce :**
visit https://shagunaawasthi.github.io/IOSD-MAIT.github.io/Workshops.html

now inspect and see error on small screen devices as well as on desktop.
![Screenshot from 2019-11-07 19-41-00](https://user-images.githubusercontent.com/46647141/68396295-58d0f480-0197-11ea-9e88-b0aca812af06.png)

![Screenshot from 2019-11-07 19-40-48](https://user-images.githubusercontent.com/46647141/68396374-7a31e080-0197-11ea-8c59-cf4a9e2a7bd3.png)

**Comment by himanshu010** [comment]
@snitin315 I will definitely work on this issue and send a pull request regarding it as soon as possible
